# docker-compose.yaml
  version: '3.3'
  services:
    jenkins:
      build: ./jenkins-master
      privileged: true
      user: root
      ports:
        - 8081:8080
        - 50000:50000
      container_name: jenkins
      volumes:
        #-/home/sanjay/jenkins/jenkins_home:/var/jenkins_home
        #- D:\jenkins\jenkins_home:/var/jenkins_home
        - /home/sanjay/Documents/project-data/jenkins/jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock